# This file intentionally left blank

BOARD = GENERIC_RP_RP2040

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

RGBLIGHT_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
WS2812_DRIVER = vendor



SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

